best_model_path: ckpt/best_model_multi.pth

data:
  name: Metro_Interstate_Traffic_Volume
  path: /home/pod/alex/ML/20241120/data/features.csv
  time_step: 24

model:
  name: MultiLSTM
  conv1d:
    in_channels: 24
    out_channels: 24
    kernel_size: 1
  input_size: 1
  hidden_size: 128
  num_layers: 5
  dropout: 0.2
  bidirectional: False

train:
  batch_size: 64
  epochs: 100
  lr: 0.001
  seed: 42
  early_stopping_patience: 10
  epochs_no_improve: 5
