best_model_path: ckpt/best_model_single.pth

data:
  name: Metro_Interstate_Traffic_Volume
  path: /home/pod/shared-nvme/datasets/Metro_Interstate_Traffic_Volume.csv
  time_step: 130

model:
  name: LSTM
  conv1d:
    in_channels: 130
    out_channels: 130
    kernel_size: 1
  input_size: 1
  hidden_size: 128
  num_layers: 5
  dropout: 0.2
  bidirectional: True

train:
  batch_size: 64
  epochs: 100
  lr: 0.001
  early_stopping_patience: 10
  seed: 42
